# Generated by Django 3.0.5 on 2020-11-13 10:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=2)),
                ('datetime', models.DateTimeField(max_length=8)),
                ('aadhar_number', models.CharField(max_length=12)),
                ('phone_number', models.CharField(max_length=10)),
                ('father_name', models.CharField(max_length=50)),
                ('mother_name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('state', models.CharField(max_length=20)),
                ('district', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=20)),
                ('blood_group', models.CharField(max_length=3)),
                ('number_of_family_members', models.CharField(max_length=2)),
                ('proffesion', models.CharField(max_length=30)),
                ('annual_income', models.CharField(max_length=10)),
                ('alt_phone_number', models.CharField(blank=True, max_length=10)),
                ('disease', models.CharField(blank=True, default='NO', max_length=20)),
                ('maritial_status', models.CharField(choices=[('M', 'Married'), ('U', 'Unmarried')], max_length=2)),
                ('refrence_record', models.CharField(blank=True, max_length=30)),
                ('profile_status', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
