# Generated by Django 3.0.5 on 2020-11-13 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_auto_20201113_2341'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer_profile',
            old_name='datetime',
            new_name='dob',
        ),
    ]
