# Generated by Django 3.0.5 on 2020-11-13 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_auto_20201114_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_profile',
            name='profile_status',
            field=models.BooleanField(),
        ),
    ]
