# Generated by Django 3.0.5 on 2020-11-13 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_auto_20201114_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_profile',
            name='dob',
            field=models.DateField(max_length=8),
        ),
        migrations.AlterField(
            model_name='customer_profile',
            name='profile_status',
            field=models.BooleanField(default=True),
        ),
    ]
