# Generated by Django 3.0.5 on 2020-11-13 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_auto_20201114_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_profile',
            name='aadhar_number',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='customer_profile',
            name='blood_group',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=3),
        ),
        migrations.AlterField(
            model_name='customer_profile',
            name='mother_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
