# Generated by Django 3.0.5 on 2020-11-14 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_auto_20201114_0100'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_profile',
            name='picture',
            field=models.ImageField(blank=True, upload_to='profile_images'),
        ),
    ]
