# Generated by Django 3.0.5 on 2020-11-16 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0010_customer_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_profile',
            name='registered_as',
            field=models.CharField(choices=[('CUS', 'Customer')], default='CUS', max_length=3),
        ),
    ]
