# Generated by Django 3.0.5 on 2020-11-16 11:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee_Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_as', models.CharField(choices=[('EMP', 'Employee')], max_length=3)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=2)),
                ('dob', models.DateField(max_length=8)),
                ('aadhar_number', models.CharField(blank=True, max_length=12)),
                ('pan_number', models.CharField(blank=True, max_length=10)),
                ('phone_number', models.CharField(max_length=10)),
                ('qualifications', models.CharField(choices=[('10', '10'), ('12', '12'), ('UG', 'UG'), ('PG', 'PG')], max_length=2)),
                ('documents', models.FileField(blank=True, upload_to='qualification_documents')),
                ('job_experience', models.CharField(max_length=20)),
                ('father_name', models.CharField(max_length=50)),
                ('mother_name', models.CharField(blank=True, max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('state', models.CharField(max_length=20)),
                ('district', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=20)),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=3)),
                ('number_of_family_members', models.CharField(max_length=2)),
                ('alt_phone_number', models.CharField(blank=True, max_length=10)),
                ('disease', models.CharField(blank=True, default='NO', max_length=20)),
                ('maritial_status', models.CharField(choices=[('M', 'Married'), ('U', 'Unmarried')], max_length=2)),
                ('refrence_record', models.CharField(blank=True, max_length=30)),
                ('picture', models.ImageField(blank=True, upload_to='profile_images')),
                ('profile_status', models.BooleanField(default=True)),
                ('user', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
