# Generated by Django 3.0.5 on 2020-11-16 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_employee_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_profile',
            name='registered_as',
            field=models.CharField(choices=[('EMP', 'Employee')], default='EMP', max_length=3),
        ),
    ]
