# Generated by Django 3.0.5 on 2020-11-04 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='resgitration',
            fields=[
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('mobile', models.PositiveIntegerField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
    ]
