# Generated by Django 3.0.5 on 2020-11-16 21:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Business_Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_as', models.CharField(choices=[('BUSI', 'Business')], default='BUSI', max_length=4)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=2)),
                ('dob', models.DateField(max_length=8)),
                ('aadhar_number', models.CharField(blank=True, max_length=12)),
                ('phone_number', models.CharField(max_length=10)),
                ('father_name', models.CharField(max_length=50)),
                ('mother_name', models.CharField(blank=True, max_length=50)),
                ('maritial_status', models.CharField(choices=[('M', 'Married'), ('U', 'Unmarried')], max_length=2)),
                ('husband_wife_name', models.CharField(blank=True, max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('business_address', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('state', models.CharField(max_length=20)),
                ('district', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=20)),
                ('business_phone_number', models.CharField(max_length=10)),
                ('refrence_record', models.CharField(blank=True, max_length=30)),
                ('picture', models.ImageField(blank=True, upload_to='profile_images')),
                ('business_picture', models.ImageField(blank=True, upload_to='business_profile_images')),
                ('business_category', models.CharField(choices=[('MDR', 'MEDICINE RETAIL'), ('MDW', 'MEDICINE WHOLESALE'), ('MDD', 'MEDICINE DISTRIBUTOR'), ('LND', 'LABS AND DIAGNOSTIC'), ('HSP', 'HOSPITAL'), ('NH', 'NURSING HOME'), ('CLNC', 'CLINIC'), ('DOC', 'DOCTOR'), ('PTPY', 'PHYSIOTHERAPY')], max_length=4)),
                ('business_registration_number', models.CharField(max_length=20)),
                ('business_license', models.CharField(max_length=20)),
                ('business_gst_number', models.CharField(max_length=15)),
                ('documents_upload', models.FileField(blank=True, upload_to='business_documents')),
                ('profile_status', models.BooleanField(default=True)),
                ('user', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
